language: ruby
script: "bundle exec rake spec"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - jruby-19mode
gemfile:
  - gemfiles/active_record_32.gemfile
  - gemfiles/active_record_40.gemfile
notifications:
  email: false
